name: Build and push ZombieCat

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  GCP_PROJECT_ID: nuanxed-platform-lab
  GKE_CLUSTER: nuanxed-platform-lab-gke
  GKE_ZONE: europe-west1-b
  DOCKER_REGISTRY: europe-west1-docker.pkg.dev
  DOCKER_REPOSITORY: docker
  DOCKER_IMAGE: zombie-cat

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Authenticate with GCP
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.ZC_SA_BUILD_AND_DEPLOY_JSON }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
  
      - name: Connect to GKE cluster
        run: |
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      - name: Configure docker
        run: |
          gcloud auth configure-docker "$DOCKER_REGISTRY"

        name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: "$DOCKER_REGISTRY/$GCP_PROJECT_ID/$DOCKER_REPOSITORY/$DOCKER_IMAGE:$(date +%s)"