name: Build ZombieCat Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build ZombieCat Docker image
      run: docker build . --file Dockerfile --tag zombie-cat:$(date +%s)