name: Build and deploy ZombieCat

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  PROJECT_ID: nuanxed-platform-lab
  GKE_CLUSTER: nuanxed-platform-lab-gke
  GKE_ZONE: europe-west1-b
  DOCKER_REGISTRY: europe-west1-docker.pkg.dev
  DOCKER_IMAGE: zombie-cat

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Authenticate with GCP
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.ZC_SA_BUILD_AND_DEPLOY_JSON }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
  
      - name: Connect to GKE cluster
        run: |
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      - name: Configure docker
        run: |
          gcloud auth configure-docker "$DOCKER_REGISTRY"

      - name: Build
        run: |-
          docker build . \
            --file Dockerfile
            -t "$DOCKER_REGISTRY/$PROJECT_ID/$DOCKER_IMAGE:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF"
            
      - name: Publish
        run: |-
          docker push "$DOCKER_REGISTRY/$PROJECT_ID/$DOCKER_IMAGE:$GITHUB_SHA"